services:
  - type: web
    name: CavaDorada_API
    env: java
    runtime: java19
    buildCommand: "./mvnw clean install"
    startCommand: "java -jar target/Restobar-CavaDorada-0.0.1-SNAPSHOT.jar"
    autoDeploy: true
