services:
  - type: web
    name: CavaDorada_API
    env: java
    rootDir: Restobar-CavaDorada
    runtime: java19  # Cambia a 'java19' si usas Java 19
    buildCommand: "./mvnw clean install"
    startCommand: "java -jar target/Restobar-CavaDorada-0.0.1-SNAPSHOT.jar"
    autoDeploy: true
    envVars:
      - key: SPRING_DATASOURCE_URL
        value: tu_valor
      - key: SPRING_DATASOURCE_USERNAME
        value: tu_usuario
      - key: SPRING_DATASOURCE_PASSWORD
        value: tu_contraseña
